// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env.DATABASE_URL

if(!databaseUrl) {
  throw new Error("DATABASE_URL is not defined")
}

export default defineConfig({
  schema: "src/infrastructure/db/prisma/schema.prisma",
  migrations: {
    path: "src/infrastructure/db/prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
